### ISSUE TITLE
Try this for histogram...

### ISSUE THREAD

**Issue by lmushkat** [npurtell/Astr-119-Final-Project#3]
@jcmcmurry 
try this:
histogram = plt.hist(hlsp_hudf12_hst_wfc3ir_udfmain_f105w_v1.0_drz.ﬁts._data.flatten(), bins='auto')

**Comment by lmushkat** [comment]
i dont think objects is what we want
what did we name the end result of all the magnitude stuff?

**Comment by jcmcmurry** [comment]
Magnitude is still copy of online tutorial component. Code is working but not yet calculating our obejcts' magnitudes.

**Comment by jcmcmurry** [comment]
WAIT
I THINK WE JUST NEED TO PLOT THE FLUX ARRAY. AND ADJUST THAT WITH THE AB MAG CALCULATIONS
